# Generated by Django 4.1.10 on 2023-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0172_larger_power_draw_values'),
        ('netbox_plugin_mclag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcdomain',
            options={'verbose_name': 'Multi-Chassis Domain', 'verbose_name_plural': 'Multi-Chassis Domains'},
        ),
        migrations.AlterModelOptions(
            name='mclag',
            options={'verbose_name': 'Multi-Chassis Link Aggregation Group', 'verbose_name_plural': 'Multi-Chassis Link Aggregation Groups'},
        ),
        migrations.AddField(
            model_name='mclag',
            name='interfaces',
            field=models.ManyToManyField(related_name='mc_lags', to='dcim.interface'),
        ),
    ]
